### PR TITLE
Get user data after login ( + client-side socket manager + fix authentication issues)

### LINKED ISSUE #189: Get user data on login
When an existing user logs in / opens app, we need to get their data from the server and use it to populate the goals in the state

### PR DESCRIPTION
**Pull request by shiryz**
@des-des sorry this ended up getting really big...

- adds 'authenticate' event to sockets flow: we save basic info about the user in the state, and, if it's not there, send an authentication request to the server
- server decodes cookie to authenticate user, sends user id back to client, followed by all their data (goals and ratings)
- adds middleware for handling interaction of sockets / redux
- new goals created by the user are now sent to the server via the socket (middleware function checks updateCount on goals etc., as planned weeks and weeks ago (!) with @des-des -- see #137 )
- all works even when network connection down! : )

Not included in this PR: handling new ratings! that's in #260 

Question: what should we do if the user is not authenticated? not handling that at all right now. Do we need a new view (don't think we have time to create one - the situation also seems unlikely...)

^^ edited description above written by Emily 🐒

### CODE REVIEW

File: server/mock.js [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+    name: 'I will eat more pizza',
+    avatar: 'pumpkin',
+    user_id: 0,
+  },
+];
+
+module.exports = {
+  users: users,
+  goals: goals,
+};
```
Comment (emilyb7) [inline server/mock.js]: do we still need this file?

File: server/database/format-user-data.js [hunk 2]
```diff
@@ -0,0 +1,31 @@
+module.exports = (goalsArr) => {
```
Comment (emilyb7) [inline server/database/format-user-data.js]: 🙀

File: server/mock.js (hunk 1 above)
Comment (shiryz) [inline server/mock.js]: I thought I deleted it , will again

File: server/sockets.js [hunk 3]
```diff
@@ -1,12 +1,28 @@
...
+      return accept('No cookie transmitted.', false);
+    }
+
+    accept(null, true);
+  });
 
-    socket.on('newGoals', (data) => {
-      console.log(data);
+  io.on('connection', (socket) => {
+    getUserData(id, (res) => {
```
Comment (emilyb7) [inline server/sockets.js]: do we need to handle errors here?

Comment (emilyb7) [inline server/sockets.js]: Also, I think it might be better to put the file 'format-user-dater' into `/server` as it technically doesn't interact with the database. It's kind of just a helper function. Maybe it can be in a `/helpers` folder instead or something...

File: app/reducers/index.js [hunk 4]
```diff
@@ -245,6 +245,11 @@ export default (state = defaultState, action) => {
         return { ...goal, updateCount:0, syncDBCount: 0, };
       }),
     };
+  case types.RECEIVE_DB_DATA:
+    return {
+      ...state,
+      goals: action.goals,
+    };
```
Comment (emilyb7) [inline app/reducers/index.js]: probs needs a test 😬

File: server/database/get-user-data.js [hunk 5]
```diff
@@ -0,0 +1,33 @@
...
+    ratings.comment,
+    ratings.date_created
+  FROM (goals LEFT OUTER JOIN ratings ON goals.goal_id = ratings.goal_id)
+  WHERE
+    goals.user_id=$1 
+  AND
+    goals.deleted=false
+  GROUP BY goals.goal_id, ratings.rating_id
+  ORDER BY goals.goal_id, ratings.rating ASC
+`;
```
Comment (emilyb7) [inline server/database/get-user-data.js]: Just realised that we're not getting the created date for the goals! This is then missing from the frontend. As far as I can see, the goals are being ordered by their ID, which is not incremental. Therefore, goals could end up getting listed in a seemingly random order. I think we need to include the created date here, and order by date created.

File: server/helpers/format-user-data.js [hunk 6]
```diff
@@ -1,24 +1,39 @@
...
+      filteredGoals.push(goal);
     }
   });
-  // Iterate over the goals to add ratings
-  goalsArr.forEach( (goal) => {
-    goals.forEach ((formattedGoal, index) => {
-      if(goal.goal_id === goals[index].id){
-        goals[index].ratings = goal.rating ? goals[index].ratings.concat([{
+  return filteredGoals;
+};
```
Comment (emilyb7) [inline server/helpers/format-user-data.js]: again, array.filter?

File: server/helpers/format-user-data.js [hunk 7]
```diff
@@ -27,5 +42,11 @@ module.exports = (goalsArr) => {
       }
     });
   });
+  return formattedGoals;
+};
```
Comment (emilyb7) [inline server/helpers/format-user-data.js]: this is quite confusing, and it took me a while to understand what it was doing. I get it now. 

I think we could probs move the bit where we concatenate the ratings into a separate function. Also, the whole thing could be done with a combination of map / filter, which I think would be easier to understand.

Like:

```js
const matchingRatings = ratings.filter(/* find ratings with correct goal_uid*/);
goals = goals.map(goal => ({ ...goal, ratings: matchingRatings..., });
```
^^ something like that!

File: server/socket-manager.js [hunk 8]
```diff
@@ -5,9 +5,18 @@ const getUserData = require('./database/get-user-data.js');
...
+  });
+};
+
+const socketManager = (socket) => {
+  socket.on('authenticate', () => {
+    authenticateCookie(socket, (err, id) => {
+      if(err) socket.emit('User not authenticated');
+      getUserData(id, (data) => {
+        socket.emit('userdata', data);
+      });
```
Comment (emilyb7) [inline server/socket-manager.js]: what are we doing with all this on the frontend? Are we still using the on connect event? Or is this replacing it?

File: server/socket-manager.js [hunk 9]
```diff
@@ -5,9 +5,18 @@ const getUserData = require('./database/get-user-data.js');
...
-      socket.emit('userdata', data);
+    if(err) callback(err);
+    callback(null, decodedCookie.id);
+  });
+};
+
+const socketManager = (socket) => {
+  socket.on('authenticate', () => {
+    authenticateCookie(socket, (err, id) => {
+      if(err) socket.emit('User not authenticated');
```
Comment (emilyb7) [inline server/socket-manager.js]: what happens to this? can this not be a simple event name, like 'authentication_error'. We need to handle it on the frontend somehow...

File: server/helpers/format-user-data.js [hunk 10]
```diff
@@ -27,5 +42,11 @@ module.exports = (goalsArr) => {
...
+
+module.exports = (goalsArray) => {
+  let goals = removeDuplicates(formatGoalsArray(goalsArray));
+  goals = addRatings(goals, goalsArray);
   return JSON.stringify(goals);
 };
```
Comment (emilyb7) [inline server/helpers/format-user-data.js]: `const formattedGoals` then `const goalsWithRatings` ? Something like that... avoids mutation and makes it clearer what's going on...

File: server/database/get-user-data.js [hunk 11]
```diff
@@ -0,0 +1,47 @@
...
+
+const getRatingsQuery = `
+  SELECT
+    ratings.rating_id,
+    ratings.rating,
+    ratings.comment,
+    ratings.date_created
+  FROM ratings
+  WHERE user_id=$1 AND goal_id=$2
```
Comment (des-des) [inline server/database/get-user-data.js]: I expect that if `goal_id`=`$2`, it is impossible that `user_id` != `$1`
ie `user_id=$1` is unnecessary

File: server/database/handle-goal-data.js [hunk 12]
```diff
@@ -0,0 +1,40 @@
...
+  VALUES ($1, $2, $3, $4, $5)
+  RETURNING goal_id
+`;
+
+module.exports = (goal, user_id, callback) => {
+  const goalId = goal.id;
+
+  dbClient.query(getGoal, [ goalId, ], (getGoalErr, getGoalResult) => {
+    if (getGoalErr) {
+      return callback('error data from database');
```
Comment (des-des) [inline server/database/handle-goal-data.js]: I think its good to log the error if you are throwing it away.

Comment (des-des) [inline server/database/handle-goal-data.js]: You will think we when you are debugging the production db in 6 months time

File: server/socket-manager.js [hunk 13]
```diff
@@ -10,11 +14,33 @@ const authenticateCookie = (socket, callback) => {
...
+  socket.on('authenticate', (_, clientCallback) => {
+    authenticateCookie(socket, (err, id) => {
+      if (err) {
+        socket.emit('authentication_error');
+        clientCallback('auth error');
+      }
+      getUserData(id, (data) => {
+        user_id = id;
+        clientCallback(null, id);
+        socket.emit('userdata', data);
```
Comment (des-des) [inline server/socket-manager.js]: should be `user_data` or `userData`, not `userdate`.

I know this is a pain because you need to change the client so dw if this is long

File: server/socket-manager.js [hunk 14]
```diff
@@ -10,11 +14,33 @@ const authenticateCookie = (socket, callback) => {
...
 
 const socketManager = (socket) => {
-  socket.on('authenticate', () => {
-    authenticateCookie(socket, (err, data) => {
-      if(err) socket.emit('User not authenticated');
-      socket.emit('userdata', data);
-      // handles socket events
+  let user_id = '';
+
+  socket.on('authenticate', (_, clientCallback) => {
```
Comment (des-des) [inline server/socket-manager.js]: Sorry if I am being think, my brain is kind of broken now but i am confused. Surely this is not the api for `socket.on`: https://socket.io/docs/server-api/#socket-on-eventname-callback

File: server/socket-manager.js [hunk 15]
```diff
@@ -10,11 +14,33 @@ const authenticateCookie = (socket, callback) => {
...
+      }
+      getUserData(id, (data) => {
+        user_id = id;
+        clientCallback(null, id);
+        socket.emit('userdata', data);
+      });
+    });
+  });
+
+  socket.on('goal', (data, clientCallback) => {
```
Comment (des-des) [inline server/socket-manager.js]: No!

You are registering this event listener even if the socket does not authenticate!! Only register this eventListener on successful authentication!

(I think)

File: server/socket-manager.js [hunk 16]
```diff
@@ -10,11 +14,33 @@ const authenticateCookie = (socket, callback) => {
...
+    const goalData = JSON.parse(data);
+
+    handleGoalData(goalData, user_id, (err, result) => {
+      if (err) {
+        clientCallback(true);
+      } else if (result === 'goal already exists') {
```
Comment (des-des) [inline server/socket-manager.js]: Ugh, what if there is a typo in this string.

I prefer something more like `result.alreadyExists === true`

File: app/main.js [hunk 17]
```diff
@@ -1,16 +1,24 @@
...
+import socketStarter, { socketsMiddleware, } from './sockets.js';
+
+const createStoreWithMiddleware = applyMiddleware(socketsMiddleware)(createStore);
+
+const store = createStoreWithMiddleware(
+  reducer, window.devToolsExtension && window.devToolsExtension()
+);
 
-const store = createStore(Store, window.devToolsExtension && window.devToolsExtension());
+socketStarter(store);
```
Comment (emilyb7) [inline app/main.js]: oops!

File: app/sockets.js [hunk 18]
```diff
@@ -1,5 +1,57 @@
 import io from 'socket.io-client';
 
-const socket = io();
+import {
+  receiveDbData, setPendingSyncOpen, updateSyncSuccess, updateSyncFailure, resetUpdateCount, authSuccess, } from './actions/general.js';
+import * as types from './action_types.js';let socket;
```
Comment (emilyb7) [inline app/sockets.js]: oops!

File: app/sockets.js [hunk 19]
```diff
@@ -1,5 +1,57 @@
...
+    store.dispatch(updateSyncSuccess(socketResponse.goal_id));
+  });
+
+  // set pending sync open to true
+  store.dispatch(setPendingSyncOpen(goal));
+};
+
+export const socketsMiddleware = (store) =>
+  next =>
+    action => {
```
Comment (emilyb7) [inline app/sockets.js]: 👍🏻

File: app/sockets.js [hunk 20]
```diff
@@ -1,5 +1,57 @@
...
+        if (action.type === types.SET_AUTH_PENDING) {
+          socket.emit('authenticate', null, (socketErr, user_id) => {
+            if (socketErr) {
+              return store.dispatch(authFailure());
+            }
+            return store.dispatch(authSuccess(user_id));
+          });
+        }
+        const goals = store.getState().goals;
+        if (!window.navigator.onLine) return;
```
Comment (emilyb7) [inline app/sockets.js]: um, cancels the whole lot if there's no network connection...? right?

File: app/sockets.js [hunk 21]
```diff
@@ -1,5 +1,57 @@
...
+        goals.forEach((goal) => {
+          if (goal.pendingSync && goal.pendingSync.open) return;
+          if (goal.updateCount > 0 && goal.updateCount === goal.syncDBCount) {
+            return store.dispatch(resetUpdateCount(goal.id));
+          }
+          if (goal.updateCount === goal.syncDBCount) return;
+          startSyncGoal(goal, store);
```
Comment (emilyb7) [inline app/sockets.js]: 👍🏻

File: server/socket-manager.js (hunk 14 above)
Comment (shiryz) [inline server/socket-manager.js]: @emilyb7 , I'm leaving this backend one for you :smile:

File: server/socket-manager.js (hunk 16 above)
Comment (emilyb7) [inline server/socket-manager.js]: oops, this was just me testing stuff out. It's already fixed on another branch!

File: server/socket-manager.js (hunk 14 above)
Comment (emilyb7) [inline server/socket-manager.js]: @des-des not sure where the problem is... it works (so far)! here're the docs I found:
https://socket.io/docs/#sending-and-getting-data-(acknowledgements)

**Comment by emilyb7** [comment]
things I think we should still fix:
- get date for all goals 
- send dates to frontend and order goals by date (probably sort first in SQL)
- convert dates (goals and ratings) to JS date object (currently a string)

File: server/socket-manager.js (hunk 14 above)
Comment (des-des) [inline server/socket-manager.js]: @emilyb7 thnxs for the link. You are correct

**Comment by des-des** [comment]
You are both amazing

**Comment by emilyb7** [comment]
@des-des thanks ;) I had actually just unassigned you because there's something wrong and it doesn't work any more! 🙈 new PR coming soonish...
